### PR TITLE
Dev interpreter

### PR DESCRIPTION
**Pull request by AStenbaek**

### CODE REVIEW

**Review by Armael — COMMENTED** [review]
Looks good! I only had minor (mostly stylistic) comments -- see below.

Additionally, menhir says that there is a shift/reduce conflict in the parser, it would be nice to see if that can be fixed.

**Review by Armael — COMMENTED** [review]
looks good!

**Comment by Armael** [comment]
I've pushed some tweaks and basic scaffolding for an interactive interpreter. Right now I've only implemented a panel to display the state of registers.

**Comment by BastienRousseau** [comment]
I extracted the interpreter into its own repository [cerise-interpreter](https://github.com/logsem/cerise-interpreter), thus I close the PR.

**Pull request closed without merging**
